version: 2.1

jobs:
  build:
    docker: 
      - image: docker.io/golang:1.19-alpine
    
    steps: 
      - checkout

      - run:
          name: Initialize Env file
          command:  |
            echo "
              JWT_ACCESS_SECRET=$JWT_ACCESS_SECRET
              SERVER_PORT=$SERVER_PORT
              JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET
              JWT_ACCESS_TOKEN_EXPIRES_AT=$JWT_ACCESS_TOKEN_EXPIRES_AT
              JWT_REFRESH_TOKEN_EXPIRES_AT=$JWT_REFRESH_TOKEN_EXPIRES_AT
            " > .env

      - run:
          name: Build repo
          command:  |
            go build main.go
    
      - run:
          name:  start the service
          command: | 
            ./main
          background: true

  
  deploy_to_develop:
    docker: 
      - image: google/cloud-sdk

    steps:  
      - checkout
    
      - run: 
          name: Initialize Env file
          command:  |
            echo "
              JWT_ACCESS_SECRET=$JWT_ACCESS_SECRET
              JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET
              JWT_ACCESS_TOKEN_EXPIRES_AT=$JWT_ACCESS_TOKEN_EXPIRES_AT
              JWT_REFRESH_TOKEN_EXPIRES_AT=$JWT_REFRESH_TOKEN_EXPIRES_AT
            " > .env
      
      - run:
          name: Authenticating and configuring the Google Cloud Platform
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode | gcloud auth activate-service-account  --key-file=-
            gcloud --quiet config set project $GCLOUD_PROJECT_ID

      - deploy:
          name: Deploy to Google App Engine
          command: |
            gcloud app deploy app.yml --project $GCLOUD_PROJECT_ID  --quiet 


workflows:
  version: 2
  dev_workflow:
    jobs:
      - build:
          context: chat_app_dev
          filters:
            branches:
              only:
                - main
                - /LEAR-.*/

      - deploy_to_develop:
          context: chat_app_dev
          filters:
            branches:
              only:
                - main
          requires:
            - build